//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApplication.ClientService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RequestStudy", ReplyAction="http://tempuri.org/IService/RequestStudyResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StudyId")]
        int RequestStudy(int ClientId, string Brand);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RequestStudy", ReplyAction="http://tempuri.org/IService/RequestStudyResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StudyId")]
        System.Threading.Tasks.Task<int> RequestStudyAsync(int ClientId, string Brand);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CancelStudy", ReplyAction="http://tempuri.org/IService/CancelStudyResponse")]
        ClientApplication.ClientService.CancelStudyResponse CancelStudy(ClientApplication.ClientService.CancelStudyRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CancelStudy", ReplyAction="http://tempuri.org/IService/CancelStudyResponse")]
        System.Threading.Tasks.Task<ClientApplication.ClientService.CancelStudyResponse> CancelStudyAsync(ClientApplication.ClientService.CancelStudyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelStudy", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CancelStudyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int StudyId;
        
        public CancelStudyRequest() {
        }
        
        public CancelStudyRequest(int StudyId) {
            this.StudyId = StudyId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelStudyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CancelStudyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int StudyId;
        
        public CancelStudyResponse() {
        }
        
        public CancelStudyResponse(int StudyId) {
            this.StudyId = StudyId;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : ClientApplication.ClientService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ClientApplication.ClientService.IService>, ClientApplication.ClientService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int RequestStudy(int ClientId, string Brand) {
            return base.Channel.RequestStudy(ClientId, Brand);
        }
        
        public System.Threading.Tasks.Task<int> RequestStudyAsync(int ClientId, string Brand) {
            return base.Channel.RequestStudyAsync(ClientId, Brand);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApplication.ClientService.CancelStudyResponse ClientApplication.ClientService.IService.CancelStudy(ClientApplication.ClientService.CancelStudyRequest request) {
            return base.Channel.CancelStudy(request);
        }
        
        public void CancelStudy(ref int StudyId) {
            ClientApplication.ClientService.CancelStudyRequest inValue = new ClientApplication.ClientService.CancelStudyRequest();
            inValue.StudyId = StudyId;
            ClientApplication.ClientService.CancelStudyResponse retVal = ((ClientApplication.ClientService.IService)(this)).CancelStudy(inValue);
            StudyId = retVal.StudyId;
        }
        
        public System.Threading.Tasks.Task<ClientApplication.ClientService.CancelStudyResponse> CancelStudyAsync(ClientApplication.ClientService.CancelStudyRequest request) {
            return base.Channel.CancelStudyAsync(request);
        }
    }
}
